# Comparison between epitopes found by AlphaSeq (manuscript) and through PDB scanning
The below notebook takes a quick look at the data collected in the manuscript about epitope prediction and the regions identified in the crystaligraphic data from PDB. Specific regions were not specifically annotated, only residues. Therefore below we will simply look to see if residues identified by the AlphaSeq assay coorespond to residues that are also identified in the PDB files. For sequential epitopes, we should expect a region about 10 - 20 amino acids in size. Confirmational epitope would be more difficult to review in this manner.

## Dependencies

In [1]:
import pandas as pd
import numpy as np

## Reference data
Using supplemental table 8 (`./manuscript_data/supp_tbl_8-epitope_comparison_filtered_results.csv`) and the `interacting_residues.csv` data for comparison. Initially, I'll drop the coordinate columns to reduce the amount of data on the screen.

In [2]:
manu_epi_data = pd.read_csv("manuscript_data/supp_tbl_8-epitope_comparison_filtered_results.csv")
pdb_epi_data = pd.read_csv("additional_data/interacting_residues.csv")
coord_cols = list(pdb_epi_data.columns.str.extract(pat = r"(^[\w]*coord_.)")[0].dropna())
pdb_epi_data.drop(coord_cols, axis = 1, inplace = True)
comparison_pos = [385, 408, 417, 443, 444, 455, 460, 475, 476, 483, 484, 487, 489, 494, 496, 499, 500, 502]

Review the first three antibodies annotated in the figure of the paper, including Cilgavimab, Tixagevimab, Bamlanivimab.

In [3]:
manu_epi_data.iloc[0:3,].fillna(".")

Name 385 408 417 443   444  455 460 475  476  483   484 487   489  \
0    Cilgavimab   .   .   .   .  24.0    .   .   .    .    .     .   .     .   
1   Tixagevimab   .   .   .   .     .    .   .   .  4.0    .     .   .  19.0   
2  Bamlanivimab   .   .   .   .     .  5.0   .   .    .  4.0  14.0   .     .   

  494 496 499 500 502  
0   .   .   .   .   .  
1   .   .   .   .   .  
2   .   .   .   .   .

Below is the data from the PDB scanning for the same antibody. Note residue position K444 has repeated interactions with 3 different residues in the antibody (Y104, D107, and V109) while S443 from the spike protein also interacts with G110 and P111 from the antibody, yet this interaction was not captured in the AlphaSeq assay with the algorithm for epitope detection currently used. Additionally this could be interpreted as while the crystalographic data suggest there is an interaction, the interaction at those residues does not serve a practical purpose for the protein-protein interaction.

In [4]:
pdb_epi_data[(pdb_epi_data["Antibody"].isin(["Cilgavimab"]) & pdb_epi_data["residnum"].isin(comparison_pos))]

Antibody    Short_Name PDB_id Primary_Chains Secondary_Chains chain  \
335  Cilgavimab  CoV_binder_7   8SUO              a               im     a   
336  Cilgavimab  CoV_binder_7   8SUO              a               im     a   
337  Cilgavimab  CoV_binder_7   8SUO              a               im     a   
338  Cilgavimab  CoV_binder_7   8SUO              a               im     a   
339  Cilgavimab  CoV_binder_7   8SUO              a               im     a   
352  Cilgavimab  CoV_binder_7   8SUO              a               im     a   
353  Cilgavimab  CoV_binder_7   8SUO              a               im     a   

     residnum resid int_chain  int_residnum int_resid  int_dist   CA_dist  
335       443     S         i           110         G  3.185439  5.397681  
336       443     S         i           111         P  2.946872  5.688875  
337       444     K         i           104         Y  2.622558  8.221748  
338       444     K         i           107         D  2.663508  9.828734  
339       444     K         i           109         V  3.170898  7.528678  
352       494     S         m            34         N  3.487026  4.845880  
353       499     P         i           111         P  3.953788  6.866129

Moving on to the second antibody, Tixagevimab, it is noted from the AlphaSeq data that there may be an interaction at position 476 and 489 in the spike protein. The PDB data also identifies interacting residues at those positions (G476 and Y489), yet also identifies A475, E484, and N487 of the spike protein. Similar to the previous antibody, we can see a greater number of interactions from the PDB files, yet we are uncertain if they have practical implications to drive affinity or if the AlphaSeq assay / algorithm is under powered at detecting the interactions.

In [5]:
pdb_epi_data[(pdb_epi_data["Antibody"].isin(["Tixagevimab"]) & pdb_epi_data["residnum"].isin(comparison_pos))]

Antibody    Short_Name PDB_id Primary_Chains Secondary_Chains chain  \
292  Tixagevimab  CoV_binder_6   7L7D              e               hl     e   
293  Tixagevimab  CoV_binder_6   7L7D              e               hl     e   
294  Tixagevimab  CoV_binder_6   7L7D              e               hl     e   
295  Tixagevimab  CoV_binder_6   7L7D              e               hl     e   
296  Tixagevimab  CoV_binder_6   7L7D              e               hl     e   
297  Tixagevimab  CoV_binder_6   7L7D              e               hl     e   
298  Tixagevimab  CoV_binder_6   7L7D              e               hl     e   
303  Tixagevimab  CoV_binder_6   7L7D              e               hl     e   
304  Tixagevimab  CoV_binder_6   7L7D              e               hl     e   
317  Tixagevimab  CoV_binder_6   7L7D              e               hl     e   
318  Tixagevimab  CoV_binder_6   7L7D              e               hl     e   
319  Tixagevimab  CoV_binder_6   7L7D              e               hl     e   
321  Tixagevimab  CoV_binder_6   7L7D              e               hl     e   
322  Tixagevimab  CoV_binder_6   7L7D              e               hl     e   
323  Tixagevimab  CoV_binder_6   7L7D              e               hl     e   

     residnum resid int_chain  int_residnum int_resid  int_dist    CA_dist  
292       455     L         h            54         G  3.575225   7.629713  
293       455     L         h            55         S  3.622492   7.283007  
294       475     A         h           105         S  3.752469   5.939778  
295       475     A         h           106         C  2.876916   5.750251  
296       476     G         h           105         S  3.876849   5.272622  
297       476     G         h           106         C  3.390194   4.593737  
298       476     G         h           108         D  3.675924   5.777373  
303       484     E         l            94         S  3.470026   5.875358  
304       484     E         l            95         S  3.717014   6.419133  
317       487     N         h           106         C  3.601919   7.352470  
318       487     N         h           107         N  2.866691   8.594552  
319       487     N         h           108         D  3.923796   7.367015  
321       489     Y         h            33         A  3.764493  10.788005  
322       489     Y         h            50         W  3.938061  13.250407  
323       489     Y         h            52         V  3.554843   8.523046

Lastly, the antibody Bamlanivimab shows a good number of interactions between the antibody and spike protein from SARS-CoV-2, including interactions at R408, L455, V483, E484, Y489, and S494. The data from AlphaSeq identifies half of these positions (455, 483, and 484), though they seem to be the most prominent since both positions 483 and 484 from the spike protein interact with 4 different positions each on the antibody.

In [6]:
pdb_epi_data[(pdb_epi_data["Antibody"].isin(["Bamlanivimab"]) & pdb_epi_data["residnum"].isin(comparison_pos))]

Antibody    Short_Name PDB_id Primary_Chains Secondary_Chains chain  \
183  Bamlanivimab  CoV_binder_3   7KMG             cf             abde     c   
185  Bamlanivimab  CoV_binder_3   7KMG             cf             abde     c   
191  Bamlanivimab  CoV_binder_3   7KMG             cf             abde     c   
192  Bamlanivimab  CoV_binder_3   7KMG             cf             abde     c   
193  Bamlanivimab  CoV_binder_3   7KMG             cf             abde     c   
194  Bamlanivimab  CoV_binder_3   7KMG             cf             abde     c   
195  Bamlanivimab  CoV_binder_3   7KMG             cf             abde     c   
196  Bamlanivimab  CoV_binder_3   7KMG             cf             abde     c   
197  Bamlanivimab  CoV_binder_3   7KMG             cf             abde     c   
198  Bamlanivimab  CoV_binder_3   7KMG             cf             abde     c   
206  Bamlanivimab  CoV_binder_3   7KMG             cf             abde     c   
207  Bamlanivimab  CoV_binder_3   7KMG             cf             abde     c   
216  Bamlanivimab  CoV_binder_3   7KMG             cf             abde     c   
217  Bamlanivimab  CoV_binder_3   7KMG             cf             abde     c   
228  Bamlanivimab  CoV_binder_3   7KMG             cf             abde     f   
230  Bamlanivimab  CoV_binder_3   7KMG             cf             abde     f   
235  Bamlanivimab  CoV_binder_3   7KMG             cf             abde     f   
236  Bamlanivimab  CoV_binder_3   7KMG             cf             abde     f   
237  Bamlanivimab  CoV_binder_3   7KMG             cf             abde     f   
238  Bamlanivimab  CoV_binder_3   7KMG             cf             abde     f   
239  Bamlanivimab  CoV_binder_3   7KMG             cf             abde     f   
240  Bamlanivimab  CoV_binder_3   7KMG             cf             abde     f   
241  Bamlanivimab  CoV_binder_3   7KMG             cf             abde     f   
242  Bamlanivimab  CoV_binder_3   7KMG             cf             abde     f   
258  Bamlanivimab  CoV_binder_3   7KMG             cf             abde     f   

     residnum resid int_chain  int_residnum int_resid  int_dist    CA_dist  
183       408     R         d           106         Y  3.524177  10.201917  
185       455     L         a           103         A  3.699446   8.409169  
191       483     V         a            50         R  3.933883   8.653796  
192       483     V         a            59         N  3.688816   6.778145  
193       483     V         b            94         T  3.929851   6.335076  
194       483     V         b            96         R  3.713185   9.691079  
195       484     E         a            50         R  2.545656  10.376392  
196       484     E         a           101         Y  3.673658   6.933332  
197       484     E         a           110         Y  3.520228   8.422832  
198       484     E         b            96         R  2.971271  10.455122  
206       489     Y         a           110         Y  3.707501  11.083686  
207       489     Y         b            32         Y  3.533272  13.441347  
216       494     S         a            31         N  3.341265   7.564291  
217       494     S         a           102         E  2.869292   8.170796  
228       408     R         a           106         Y  3.276505  10.262538  
230       455     L         d           103         A  3.808130   8.632047  
235       483     V         d            50         R  3.968754   8.499330  
236       483     V         d            59         N  3.905004   6.652061  
237       483     V         e            94         T  3.907313   6.391945  
238       483     V         e            96         R  3.519923   9.657282  
239       484     E         d            50         R  2.805582  10.180630  
240       484     E         d           101         Y  3.619544   6.938253  
241       484     E         d           110         Y  3.578381   8.356039  
242       484     E         e            96         R  2.711450  10.508425  
258

## Conclusions
There appears to be a consistent agreement between the PDB structures and the AlphaSeq data, though it is unclear if the PDB data is over-sensitive to detection PPI or if the AlphaSeq assay / algorithm is underpowered to detect such interacitons. As it is often in biology, both may be true or to phrase it a different way, the answer may be a bit of both. For the next steps, I'll look into ways to improved the epitope discovery power using the AlphaSeq assay data.

A reasonable appraoch to measuring the accuracy may be in measuring the Jaccard Index (ratio of the intersection to union) of the regions detected as epitopes by the AlphaSeq assay given the PDB data is the ground truth. Below is a quick example and estimate of the accuracy by Jaccard Index of the current algorithm. This should serve as a measure of performance.

In [7]:
# Unique regions of the AlphaSeq Data
melted_manu_data = manu_epi_data.melt(id_vars = ["Name"], var_name = "pos", value_name = "score")
melted_manu_data["score"] = melted_manu_data["score"].notna()
melted_manu_data = melted_manu_data[melted_manu_data["score"]]
melted_manu_data = melted_manu_data[["Name", "pos"]]
melted_manu_data["pos"] = melted_manu_data["pos"].astype(str)

In [8]:
melted_pdb_data = pdb_epi_data[pdb_epi_data["residnum"].isin(comparison_pos)]
melted_pdb_data = melted_pdb_data[["Antibody", "residnum"]]
melted_pdb_data = melted_pdb_data.drop_duplicates()
melted_pdb_data[["Name", "pos"]] = melted_pdb_data[["Antibody", "residnum"]]
melted_pdb_data = melted_pdb_data[["Name", "pos"]]
melted_pdb_data["pos"] = melted_pdb_data["pos"].astype(str)

In [10]:
joint_abs = list(pd.merge(
        pd.DataFrame({"Name": list(set(melted_manu_data["Name"]))}),
        pd.DataFrame({"Name": list(set(melted_pdb_data["Name"]))}),
        on = "Name",
        how = "inner"
    )["Name"])

melted_pdb_fil = melted_pdb_data[melted_pdb_data["Name"].isin(joint_abs)]
melted_manu_fil = melted_manu_data[melted_manu_data["Name"].isin(joint_abs)]

intersection_length = len(pd.merge(melted_manu_fil, melted_pdb_fil, on = ["Name", "pos"], how = "inner"))
union_length = len(pd.merge(melted_manu_fil, melted_pdb_fil, on = ["Name", "pos"], how = "outer"))
print(f"Intersection: {intersection_length}\nUnion: {union_length}\nJaccard Index: {intersection_length / union_length}")

Intersection: 25
Union: 100
Jaccard Index: 0.25


In [11]:
melted_pdb_data_unfiltered = pdb_epi_data
melted_pdb_data_unfiltered = melted_pdb_data_unfiltered[["Antibody", "residnum"]]
melted_pdb_data_unfiltered = melted_pdb_data_unfiltered.drop_duplicates()
melted_pdb_data_unfiltered[["Name", "pos"]] = melted_pdb_data_unfiltered[["Antibody", "residnum"]]
melted_pdb_data_unfiltered = melted_pdb_data_unfiltered[["Name", "pos"]]
melted_pdb_data_unfiltered["pos"] = melted_pdb_data_unfiltered["pos"].astype(str)

melted_pdb_unfil = melted_pdb_data_unfiltered[melted_pdb_data_unfiltered["Name"].isin(joint_abs)]

intersection_length = len(pd.merge(melted_manu_fil, melted_pdb_unfil, on = ["Name", "pos"], how = "inner"))
union_length = len(pd.merge(melted_manu_fil, melted_pdb_unfil, on = ["Name", "pos"], how = "outer"))
print(f"Intersection: {intersection_length}\nUnion: {union_length}\nJaccard Index: {intersection_length / union_length}")

Intersection: 25
Union: 316
Jaccard Index: 0.07911392405063292
